from loginrequest import LoginRequest
from menurequest import MenuRequest, DeliveryMethod
from adddishrequest import AddDishRequest
from getpaymentrequest import GetPaymentRequest
from submitorderrequest import SubmitOrderRequest